# Generated by Django 5.0.3 on 2024-03-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="birthdate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(max_length=50, null=True),
        ),
    ]
