# Generated by Django 5.0.3 on 2024-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_about_profile_birthdate_profile_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="Profiles"),
        ),
    ]
