# Generated by Django 5.0.3 on 2024-03-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_birthdate_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="Profiles/default-user.png",
                null=True,
                upload_to="Profiles",
            ),
        ),
    ]
