# Generated by Django 5.0.3 on 2024-03-20 00:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_post", "0002_rename_features_category_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
